import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { gzipSync } from "node:zlib";
import { build } from "esbuild";

const require = createRequire(import.meta.url);
const packages: Record<string, string> = {
    util: "util/",
    events: "events/",
    assert: "assert/",
    stream: "stream-browserify",
    crypto: "crypto-browserify",
    zlib: "browserify-zlib",
    buffer: "buffer/",
    string_decoder: "string_decoder/",
    querystring: "querystring-es3",
    "url-browser": "url/",
};
const adapters: Record<string, string> = {
    path: "path",
    "path/win32": "path-win32",
    fs: "fs",
    "fs/promises": "fs-promises",
    process: "process",
    os: "os",
    url: "url",
    v8: "v8",
    module: "module",
    "timers/promises": "timers-promises",
    "make-fetch-happen": "transport",
    pacote: "pacote",
};
const denied = new Set(["child_process", "http", "https", "http2", "net", "tls", "dns", "worker_threads"]);
const result = await build({
    entryPoints: ["src/browser/worker/bootstrap.ts"],
    write: false,
    bundle: true,
    platform: "browser",
    format: "iife",
    minify: true,
    metafile: true,
    plugins: [
        {
            name: "browser-runtime-boundary",
            setup(context) {
                context.onResolve({ filter: /^(?:node:)?[a-z0-9_-]+(?:\/[a-z0-9_-]+)?$/ }, (args) => {
                    const name = args.path.replace(/^node:/, "");
                    if (name === "pacote-original") return { path: require.resolve("pacote") };
                    const adapter = adapters[name] ?? (denied.has(name) ? "unsupported" : undefined);
                    if (adapter)
                        return {
                            path: resolve(`src/browser/worker/adapters/${adapter}.ts`),
                            namespace: "node-export-bridge",
                        };
                    if (packages[name]) return { path: require.resolve(packages[name]) };
                    return undefined;
                });
                context.onLoad({ filter: /.*/, namespace: "node-export-bridge" }, (args) => ({
                    // Upstream require() expects a callable or object, rather than an ESM namespace.
                    // This bridge is generated; every authored adapter remains TypeScript/ESM.
                    contents: `module.exports = require(${JSON.stringify(args.path)}).default;`,
                    loader: "js",
                    resolveDir: process.cwd(),
                }));
            },
        },
    ],
    define: {
        "process.env.NODE_DEBUG": "undefined",
        __dirname: '"/__bundled__"',
        __filename: '"/__bundled__/worker.js"',
    },
});
const output = result.outputFiles[0];
if (!output) throw new Error("Browser engine build produced no output");
await writeFile(
    "src/browser/generated.ts",
    `// Generated by build:engine; includes upstream license comments.\nexport const workerSource: string = ${JSON.stringify(output.text)};\n`,
);
await mkdir("tmp", { recursive: true });
await writeFile("tmp/engine-metafile.json", JSON.stringify(result.metafile, null, 2));
await writeFile(
    "tmp/engine-size.json",
    JSON.stringify({ bytes: output.contents.length, gzipBytes: gzipSync(output.text).length }, null, 2),
);
